<?php
/**
 * Exporter.
 *
 * Generates translation files in PO, MO, JSON, and PHP array formats.
 *
 * @package Theme_String_Translator
 * @since   1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class TST_Exporter
 *
 * Exports translations from the database into various file formats
 * for use with WordPress gettext system or external tools.
 *
 * @since 1.0.0
 */
class TST_Exporter {

	/**
	 * Translator instance.
	 *
	 * @since 1.0.0
	 * @var TST_Translator
	 */
	private $translator;

	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 *
	 * @param TST_Translator $translator The translator instance.
	 */
	public function __construct( TST_Translator $translator ) {
		$this->translator = $translator;
	}

	/**
	 * Generate a PO file string for a given locale.
	 *
	 * Creates a properly formatted PO file with headers and msgid/msgstr pairs.
	 * Handles multiline strings and escapes special characters.
	 *
	 * @since 1.0.0
	 *
	 * @param string $locale The locale code (e.g. 'pl_PL').
	 * @return string The PO file content.
	 */
	public function export_po( $locale ) {
		$translations = $this->translator->get_translations_for_locale( $locale );
		$theme        = wp_get_theme();

		$output  = "# Translation file for {$theme->get( 'Name' )}\n";
		$output .= "# Generated by Theme String Translator " . TST_VERSION . "\n";
		$output .= "#\n";
		$output .= "msgid \"\"\n";
		$output .= "msgstr \"\"\n";
		$output .= "\"Project-Id-Version: {$theme->get( 'Name' )} {$theme->get( 'Version' )}\\n\"\n";
		$output .= "\"Report-Msgid-Bugs-To: \\n\"\n";
		$output .= "\"POT-Creation-Date: " . gmdate( 'Y-m-d H:i+0000' ) . "\\n\"\n";
		$output .= "\"PO-Revision-Date: " . gmdate( 'Y-m-d H:i+0000' ) . "\\n\"\n";
		$output .= "\"Language: {$locale}\\n\"\n";
		$output .= "\"MIME-Version: 1.0\\n\"\n";
		$output .= "\"Content-Type: text/plain; charset=UTF-8\\n\"\n";
		$output .= "\"Content-Transfer-Encoding: 8bit\\n\"\n";
		$output .= "\"Plural-Forms: nplurals=2; plural=(n != 1);\\n\"\n";
		$output .= "\n";

		foreach ( $translations as $original => $translation ) {
			$output .= 'msgid ' . $this->po_encode_string( $original ) . "\n";
			$output .= 'msgstr ' . $this->po_encode_string( $translation ) . "\n";
			$output .= "\n";
		}

		return $output;
	}

	/**
	 * Generate a binary MO file for a given locale.
	 *
	 * Implements the GNU gettext MO file format with proper byte ordering,
	 * offset tables, and sorted entries.
	 *
	 * @since 1.0.0
	 *
	 * @param string $locale The locale code.
	 * @return string The binary MO file content.
	 */
	public function export_mo( $locale ) {
		$translations = $this->translator->get_translations_for_locale( $locale );

		// Sort entries by original string (required by MO format for binary search).
		ksort( $translations );

		// Add empty string header entry.
		$theme   = wp_get_theme();
		$headers = array(
			'Project-Id-Version'        => $theme->get( 'Name' ) . ' ' . $theme->get( 'Version' ),
			'Language'                   => $locale,
			'MIME-Version'              => '1.0',
			'Content-Type'             => 'text/plain; charset=UTF-8',
			'Content-Transfer-Encoding' => '8bit',
		);

		$header_string = '';
		foreach ( $headers as $key => $value ) {
			$header_string .= "{$key}: {$value}\n";
		}

		// Prepend header as the empty-string entry.
		$entries = array( '' => $header_string );
		foreach ( $translations as $original => $translation ) {
			$entries[ $original ] = $translation;
		}

		$count          = count( $entries );
		$originals      = array_keys( $entries );
		$translated     = array_values( $entries );
		$magic_number   = 0x950412de;
		$revision       = 0;
		$header_size    = 28; // 7 x 4 bytes.
		$offset_table_o = $header_size;
		$offset_table_t = $offset_table_o + $count * 8;
		$data_start     = $offset_table_t + $count * 8;

		// Build the strings data and offset tables.
		$originals_offsets  = array();
		$translated_offsets = array();
		$strings_data       = '';
		$current_offset     = $data_start;

		foreach ( $originals as $string ) {
			$length              = strlen( $string );
			$originals_offsets[] = array( $length, $current_offset );
			$strings_data       .= $string . "\0";
			$current_offset     += $length + 1;
		}

		foreach ( $translated as $string ) {
			$length                = strlen( $string );
			$translated_offsets[] = array( $length, $current_offset );
			$strings_data         .= $string . "\0";
			$current_offset       += $length + 1;
		}

		// Build the MO file.
		$output = pack( 'V', $magic_number );        // Magic number.
		$output .= pack( 'V', $revision );            // Revision.
		$output .= pack( 'V', $count );               // Number of strings.
		$output .= pack( 'V', $offset_table_o );      // Offset of original strings table.
		$output .= pack( 'V', $offset_table_t );      // Offset of translated strings table.
		$output .= pack( 'V', 0 );                    // Size of hashing table (unused).
		$output .= pack( 'V', 0 );                    // Offset of hashing table (unused).

		// Original strings offset table.
		foreach ( $originals_offsets as $offset ) {
			$output .= pack( 'V', $offset[0] );       // String length.
			$output .= pack( 'V', $offset[1] );       // String offset.
		}

		// Translated strings offset table.
		foreach ( $translated_offsets as $offset ) {
			$output .= pack( 'V', $offset[0] );       // String length.
			$output .= pack( 'V', $offset[1] );       // String offset.
		}

		// String data.
		$output .= $strings_data;

		return $output;
	}

	/**
	 * Generate a Jed-format JSON file for a given locale.
	 *
	 * Creates JSON compatible with the Jed JavaScript gettext library,
	 * suitable for use with wp_set_script_translations().
	 *
	 * @since 1.0.0
	 *
	 * @param string $locale The locale code.
	 * @return string The JSON string.
	 */
	public function export_json( $locale ) {
		$translations = $this->translator->get_translations_for_locale( $locale );

		$messages = array(
			'' => array(
				'domain' => 'messages',
				'lang'   => $locale,
			),
		);

		foreach ( $translations as $original => $translation ) {
			$messages[ $original ] = $translation;
		}

		$data = array(
			'locale_data' => array(
				'messages' => $messages,
			),
		);

		return wp_json_encode( $data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE );
	}

	/**
	 * Generate a PHP array export for a given locale.
	 *
	 * Creates a PHP file that returns an associative array of translations.
	 *
	 * @since 1.0.0
	 *
	 * @param string $locale The locale code.
	 * @return string The PHP file content.
	 */
	public function export_php_array( $locale ) {
		$translations = $this->translator->get_translations_for_locale( $locale );

		$output = "<?php\nreturn array(\n";
		foreach ( $translations as $key => $value ) {
			$key   = str_replace( "'", "\\'", $key );
			$value = str_replace( "'", "\\'", $value );
			$output .= "\t'" . $key . "' => '" . $value . "',\n";
		}
		$output .= ");\n";
		return $output;
	}

	/**
	 * Write PO and MO files to the active theme's languages directory.
	 *
	 * Creates the languages directory if it does not exist and writes both
	 * .po and .mo files using the text_domain-locale naming convention.
	 *
	 * @since 1.0.0
	 *
	 * @param string $locale The locale code.
	 * @return array|WP_Error Array with written file paths on success, WP_Error on failure.
	 */
	public function write_to_theme( $locale ) {
		$theme     = wp_get_theme();
		$theme_dir = get_stylesheet_directory();
		$lang_dir  = $theme_dir . '/languages';

		// Create languages directory if it does not exist.
		if ( ! is_dir( $lang_dir ) ) {
			if ( ! wp_mkdir_p( $lang_dir ) ) {
				return new \WP_Error(
					'tst_mkdir_failed',
					__( 'Failed to create the languages directory in the theme.', 'theme-string-translator' ),
					array( 'status' => 500 )
				);
			}
		}

		$text_domain = $theme->get( 'TextDomain' );
		if ( empty( $text_domain ) ) {
			$text_domain = $theme->get_stylesheet();
		}

		$locale    = sanitize_text_field( $locale );
		$base_name = $text_domain . '-' . $locale;

		// Write PO file.
		$po_content = $this->export_po( $locale );
		$po_path    = $lang_dir . '/' . $base_name . '.po';

		if ( false === file_put_contents( $po_path, $po_content ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			return new \WP_Error(
				'tst_write_po_failed',
				__( 'Failed to write the PO file.', 'theme-string-translator' ),
				array( 'status' => 500 )
			);
		}

		// Write MO file.
		$mo_content = $this->export_mo( $locale );
		$mo_path    = $lang_dir . '/' . $base_name . '.mo';

		if ( false === file_put_contents( $mo_path, $mo_content ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			return new \WP_Error(
				'tst_write_mo_failed',
				__( 'Failed to write the MO file.', 'theme-string-translator' ),
				array( 'status' => 500 )
			);
		}

		return array(
			'po' => $po_path,
			'mo' => $mo_path,
		);
	}

	/**
	 * Send a file as a download response.
	 *
	 * Sets appropriate headers and outputs the content for direct download.
	 * This method terminates script execution.
	 *
	 * @since 1.0.0
	 *
	 * @param string $content      The file content to download.
	 * @param string $filename     The download filename.
	 * @param string $content_type The MIME content type.
	 * @return void
	 */
	public function download( $content, $filename, $content_type ) {
		header( 'Content-Type: ' . $content_type );
		header( 'Content-Disposition: attachment; filename="' . sanitize_file_name( $filename ) . '"' );
		header( 'Content-Length: ' . strlen( $content ) );
		header( 'Cache-Control: no-cache, no-store, must-revalidate' );
		header( 'Pragma: no-cache' );
		header( 'Expires: 0' );

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		exit;
	}

	/**
	 * Encode a string for PO file format.
	 *
	 * Handles escaping of special characters and wrapping of multiline strings.
	 *
	 * @since 1.0.0
	 *
	 * @param string $string The string to encode.
	 * @return string The PO-encoded string.
	 */
	private function po_encode_string( $string ) {
		$string = str_replace( '\\', '\\\\', $string );
		$string = str_replace( '"', '\\"', $string );
		$string = str_replace( "\t", '\\t', $string );

		// Handle multiline strings.
		if ( false !== strpos( $string, "\n" ) ) {
			$lines  = explode( "\n", $string );
			$output = "\"\"\n";
			foreach ( $lines as $index => $line ) {
				if ( $index < count( $lines ) - 1 ) {
					$line .= '\\n';
				}
				$output .= '"' . $line . "\"\n";
			}
			return rtrim( $output, "\n" );
		}

		return '"' . $string . '"';
	}
}
